// Minecraft 1.20.1 全ブロック定義
// BUILDING_BLOCKS - 建築ブロック

const BUILDING_BLOCKS_COMPREHENSIVE = [
// 石材系
{text: '石', value: 'stone'},
{text: '滑らかな石', value: 'smooth_stone'},
{text: '滑らかな石のハーフブロック', value: 'smooth_stone_slab'},
{text: '丸石', value: 'cobblestone'},
{text: '苔むした丸石', value: 'mossy_cobblestone'},
{text: '石レンガ', value: 'stone_bricks'},
{text: 'ひび割れた石レンガ', value: 'cracked_stone_bricks'},
{text: '苔むした石レンガ', value: 'mossy_stone_bricks'},
{text: '模様入り石レンガ', value: 'chiseled_stone_bricks'},
{text: '花崗岩', value: 'granite'},
{text: '磨かれた花崗岩', value: 'polished_granite'},
{text: '閃緑岩', value: 'diorite'},
{text: '磨かれた閃緑岩', value: 'polished_diorite'},
{text: '安山岩', value: 'andesite'},
{text: '磨かれた安山岩', value: 'polished_andesite'},
{text: 'カルサイト', value: 'calcite'},
{text: 'タフ', value: 'tuff'},
{text: 'ドリップストーンブロック', value: 'dripstone_block'},

// ディープスレート系
{text: 'ディープスレート', value: 'deepslate'},
{text: '丸石状ディープスレート', value: 'cobbled_deepslate'},
{text: '磨かれたディープスレート', value: 'polished_deepslate'},
{text: 'ディープスレートレンガ', value: 'deepslate_bricks'},
{text: 'ディープスレートタイル', value: 'deepslate_tiles'},
{text: '模様入りディープスレート', value: 'chiseled_deepslate'},

// レンガ類
{text: 'レンガ', value: 'bricks'},
{text: 'ネザーレンガ', value: 'nether_bricks'},
{text: 'ひび割れたネザーレンガ', value: 'cracked_nether_bricks'},
{text: '模様入りネザーレンガ', value: 'chiseled_nether_bricks'},
{text: '赤いネザーレンガ', value: 'red_nether_bricks'},
{text: 'エンドストーンレンガ', value: 'end_stone_bricks'},
{text: 'プリズマリン', value: 'prismarine'},
{text: 'プリズマリンレンガ', value: 'prismarine_bricks'},
{text: 'ダークプリズマリン', value: 'dark_prismarine'},
{text: '泥レンガ', value: 'mud_bricks'},

// 木材（全種類）
{text: 'オークの板材', value: 'oak_planks'},
{text: 'シラカバの板材', value: 'birch_planks'},
{text: 'トウヒの板材', value: 'spruce_planks'},
{text: 'ジャングルの板材', value: 'jungle_planks'},
{text: 'アカシアの板材', value: 'acacia_planks'},
{text: 'ダークオークの板材', value: 'dark_oak_planks'},
{text: 'マングローブの板材', value: 'mangrove_planks'},
{text: 'サクラの板材', value: 'cherry_planks'},
{text: '竹の板材', value: 'bamboo_planks'},
{text: '竹のモザイク', value: 'bamboo_mosaic'},
{text: '真紅の板材', value: 'crimson_planks'},
{text: '歪んだ板材', value: 'warped_planks'},

// 羊毛（全16色）
{text: '白色の羊毛', value: 'white_wool'},
{text: '橙色の羊毛', value: 'orange_wool'},
{text: '赤紫色の羊毛', value: 'magenta_wool'},
{text: '空色の羊毛', value: 'light_blue_wool'},
{text: '黄色の羊毛', value: 'yellow_wool'},
{text: '黄緑色の羊毛', value: 'lime_wool'},
{text: '桃色の羊毛', value: 'pink_wool'},
{text: '灰色の羊毛', value: 'gray_wool'},
{text: '薄灰色の羊毛', value: 'light_gray_wool'},
{text: '青緑色の羊毛', value: 'cyan_wool'},
{text: '紫色の羊毛', value: 'purple_wool'},
{text: '青色の羊毛', value: 'blue_wool'},
{text: '茶色の羊毛', value: 'brown_wool'},
{text: '緑色の羊毛', value: 'green_wool'},
{text: '赤色の羊毛', value: 'red_wool'},
{text: '黒色の羊毛', value: 'black_wool'},

// カーペット（全16色）
{text: '白色のカーペット', value: 'white_carpet'},
{text: '橙色のカーペット', value: 'orange_carpet'},
{text: '赤紫色のカーペット', value: 'magenta_carpet'},
{text: '空色のカーペット', value: 'light_blue_carpet'},
{text: '黄色のカーペット', value: 'yellow_carpet'},
{text: '黄緑色のカーペット', value: 'lime_carpet'},
{text: '桃色のカーペット', value: 'pink_carpet'},
{text: '灰色のカーペット', value: 'gray_carpet'},
{text: '薄灰色のカーペット', value: 'light_gray_carpet'},
{text: '青緑色のカーペット', value: 'cyan_carpet'},
{text: '紫色のカーペット', value: 'purple_carpet'},
{text: '青色のカーペット', value: 'blue_carpet'},
{text: '茶色のカーペット', value: 'brown_carpet'},
{text: '緑色のカーペット', value: 'green_carpet'},
{text: '赤色のカーペット', value: 'red_carpet'},
{text: '黒色のカーペット', value: 'black_carpet'},

// コンクリート（全16色）
{text: '白色のコンクリート', value: 'white_concrete'},
{text: '橙色のコンクリート', value: 'orange_concrete'},
{text: '赤紫色のコンクリート', value: 'magenta_concrete'},
{text: '空色のコンクリート', value: 'light_blue_concrete'},
{text: '黄色のコンクリート', value: 'yellow_concrete'},
{text: '黄緑色のコンクリート', value: 'lime_concrete'},
{text: '桃色のコンクリート', value: 'pink_concrete'},
{text: '灰色のコンクリート', value: 'gray_concrete'},
{text: '薄灰色のコンクリート', value: 'light_gray_concrete'},
{text: '青緑色のコンクリート', value: 'cyan_concrete'},
{text: '紫色のコンクリート', value: 'purple_concrete'},
{text: '青色のコンクリート', value: 'blue_concrete'},
{text: '茶色のコンクリート', value: 'brown_concrete'},
{text: '緑色のコンクリート', value: 'green_concrete'},
{text: '赤色のコンクリート', value: 'red_concrete'},
{text: '黒色のコンクリート', value: 'black_concrete'},

// テラコッタ（全16色）
{text: 'テラコッタ', value: 'terracotta'},
{text: '白色のテラコッタ', value: 'white_terracotta'},
{text: '橙色のテラコッタ', value: 'orange_terracotta'},
{text: '赤紫色のテラコッタ', value: 'magenta_terracotta'},
{text: '空色のテラコッタ', value: 'light_blue_terracotta'},
{text: '黄色のテラコッタ', value: 'yellow_terracotta'},
{text: '黄緑色のテラコッタ', value: 'lime_terracotta'},
{text: '桃色のテラコッタ', value: 'pink_terracotta'},
{text: '灰色のテラコッタ', value: 'gray_terracotta'},
{text: '薄灰色のテラコッタ', value: 'light_gray_terracotta'},
{text: '青緑色のテラコッタ', value: 'cyan_terracotta'},
{text: '紫色のテラコッタ', value: 'purple_terracotta'},
{text: '青色のテラコッタ', value: 'blue_terracotta'},
{text: '茶色のテラコッタ', value: 'brown_terracotta'},
{text: '緑色のテラコッタ', value: 'green_terracotta'},
{text: '赤色のテラコッタ', value: 'red_terracotta'},
{text: '黒色のテラコッタ', value: 'black_terracotta'},

// 彩釉テラコッタ（全16色）
{text: '白色の彩釉テラコッタ', value: 'white_glazed_terracotta'},
{text: '橙色の彩釉テラコッタ', value: 'orange_glazed_terracotta'},
{text: '赤紫色の彩釉テラコッタ', value: 'magenta_glazed_terracotta'},
{text: '空色の彩釉テラコッタ', value: 'light_blue_glazed_terracotta'},
{text: '黄色の彩釉テラコッタ', value: 'yellow_glazed_terracotta'},
{text: '黄緑色の彩釉テラコッタ', value: 'lime_glazed_terracotta'},
{text: '桃色の彩釉テラコッタ', value: 'pink_glazed_terracotta'},
{text: '灰色の彩釉テラコッタ', value: 'gray_glazed_terracotta'},
{text: '薄灰色の彩釉テラコッタ', value: 'light_gray_glazed_terracotta'},
{text: '青緑色の彩釉テラコッタ', value: 'cyan_glazed_terracotta'},
{text: '紫色の彩釉テラコッタ', value: 'purple_glazed_terracotta'},
{text: '青色の彩釉テラコッタ', value: 'blue_glazed_terracotta'},
{text: '茶色の彩釉テラコッタ', value: 'brown_glazed_terracotta'},
{text: '緑色の彩釉テラコッタ', value: 'green_glazed_terracotta'},
{text: '赤色の彩釉テラコッタ', value: 'red_glazed_terracotta'},
{text: '黒色の彩釉テラコッタ', value: 'black_glazed_terracotta'},

// ガラス系
{text: 'ガラス', value: 'glass'},
{text: '色付きガラス（白）', value: 'white_stained_glass'},
{text: '色付きガラス（橙）', value: 'orange_stained_glass'},
{text: '色付きガラス（赤紫）', value: 'magenta_stained_glass'},
{text: '色付きガラス（空）', value: 'light_blue_stained_glass'},
{text: '色付きガラス（黄）', value: 'yellow_stained_glass'},
{text: '色付きガラス（黄緑）', value: 'lime_stained_glass'},
{text: '色付きガラス（桃）', value: 'pink_stained_glass'},
{text: '色付きガラス（灰）', value: 'gray_stained_glass'},
{text: '色付きガラス（薄灰）', value: 'light_gray_stained_glass'},
{text: '色付きガラス（青緑）', value: 'cyan_stained_glass'},
{text: '色付きガラス（紫）', value: 'purple_stained_glass'},
{text: '色付きガラス（青）', value: 'blue_stained_glass'},
{text: '色付きガラス（茶）', value: 'brown_stained_glass'},
{text: '色付きガラス（緑）', value: 'green_stained_glass'},
{text: '色付きガラス（赤）', value: 'red_stained_glass'},
{text: '色付きガラス（黒）', value: 'black_stained_glass'},
{text: '色付きガラス板（白）', value: 'white_stained_glass_pane'},
{text: '色付きガラス板（黒）', value: 'black_stained_glass_pane'},

// クォーツ系
{text: 'クォーツブロック', value: 'quartz_block'},
{text: '滑らかなクォーツ', value: 'smooth_quartz'},
{text: 'クォーツレンガ', value: 'quartz_bricks'},
{text: 'クォーツの柱', value: 'quartz_pillar'},
{text: '模様入りクォーツブロック', value: 'chiseled_quartz_block'},

// 砂岩系
{text: '砂岩', value: 'sandstone'},
{text: '滑らかな砂岩', value: 'smooth_sandstone'},
{text: '模様入り砂岩', value: 'chiseled_sandstone'},
{text: '模様入り赤い砂岩', value: 'chiseled_red_sandstone'},
{text: '赤い砂岩', value: 'red_sandstone'},
{text: '滑らかな赤い砂岩', value: 'smooth_red_sandstone'},

// 全ハーフブロック（全木材種類）
{text: '石のハーフブロック', value: 'stone_slab'},
{text: '丸石のハーフブロック', value: 'cobblestone_slab'},
{text: '石レンガのハーフブロック', value: 'stone_brick_slab'},
{text: 'レンガのハーフブロック', value: 'brick_slab'},
{text: 'ネザーレンガのハーフブロック', value: 'nether_brick_slab'},
{text: 'クォーツのハーフブロック', value: 'quartz_slab'},
{text: '砂岩のハーフブロック', value: 'sandstone_slab'},
{text: '赤い砂岩のハーフブロック', value: 'red_sandstone_slab'},
{text: 'プリズマリンのハーフブロック', value: 'prismarine_slab'},
{text: 'オークのハーフブロック', value: 'oak_slab'},
{text: 'シラカバのハーフブロック', value: 'birch_slab'},
{text: 'トウヒのハーフブロック', value: 'spruce_slab'},
{text: 'ジャングルのハーフブロック', value: 'jungle_slab'},
{text: 'アカシアのハーフブロック', value: 'acacia_slab'},
{text: 'ダークオークのハーフブロック', value: 'dark_oak_slab'},
{text: 'マングローブのハーフブロック', value: 'mangrove_slab'},
{text: 'サクラのハーフブロック', value: 'cherry_slab'},
{text: '竹のハーフブロック', value: 'bamboo_slab'},
{text: '竹のモザイクハーフブロック', value: 'bamboo_mosaic_slab'},
{text: '真紅のハーフブロック', value: 'crimson_slab'},
{text: '歪んだハーフブロック', value: 'warped_slab'},

// 垂直ハーフブロック（MOD追加ブロック）
{text: 'オークのスラブ（垂直）', value: 'vertical_oak_slab'},

// 全階段（全木材種類）
{text: '石の階段', value: 'stone_stairs'},
{text: '丸石の階段', value: 'cobblestone_stairs'},
{text: '石レンガの階段', value: 'stone_brick_stairs'},
{text: 'レンガの階段', value: 'brick_stairs'},
{text: 'ネザーレンガの階段', value: 'nether_brick_stairs'},
{text: 'クォーツの階段', value: 'quartz_stairs'},
{text: '砂岩の階段', value: 'sandstone_stairs'},
{text: '赤い砂岩の階段', value: 'red_sandstone_stairs'},
{text: 'プリズマリンの階段', value: 'prismarine_stairs'},
{text: 'プリズマリンレンガの階段', value: 'prismarine_brick_stairs'},
{text: 'ダークプリズマリンの階段', value: 'dark_prismarine_stairs'},
{text: 'オークの階段', value: 'oak_stairs'},
{text: 'シラカバの階段', value: 'birch_stairs'},
{text: 'トウヒの階段', value: 'spruce_stairs'},
{text: 'ジャングルの階段', value: 'jungle_stairs'},
{text: 'アカシアの階段', value: 'acacia_stairs'},
{text: 'ダークオークの階段', value: 'dark_oak_stairs'},
{text: 'マングローブの階段', value: 'mangrove_stairs'},
{text: 'サクラの階段', value: 'cherry_stairs'},
{text: '竹の階段', value: 'bamboo_stairs'},
{text: '竹のモザイク階段', value: 'bamboo_mosaic_stairs'},
{text: '真紅の階段', value: 'crimson_stairs'},
{text: '歪んだ階段', value: 'warped_stairs'},
{text: 'エンドストーンレンガの階段', value: 'end_stone_brick_stairs'},
{text: '安山岩の階段', value: 'andesite_stairs'},
{text: '磨かれた安山岩の階段', value: 'polished_andesite_stairs'},
{text: '閃緑岩の階段', value: 'diorite_stairs'},
{text: '磨かれた閃緑岩の階段', value: 'polished_diorite_stairs'},
{text: '花崗岩の階段', value: 'granite_stairs'},
{text: '磨かれた花崗岩の階段', value: 'polished_granite_stairs'},

// 塀
{text: '丸石の塀', value: 'cobblestone_wall'},
{text: '苔むした丸石の塀', value: 'mossy_cobblestone_wall'},
{text: '石レンガの塀', value: 'stone_brick_wall'},
{text: 'レンガの塀', value: 'brick_wall'},
{text: 'ネザーレンガの塀', value: 'nether_brick_wall'},
{text: '赤いネザーレンガの塀', value: 'red_nether_brick_wall'},
{text: '砂岩の塀', value: 'sandstone_wall'},
{text: '赤い砂岩の塀', value: 'red_sandstone_wall'},
{text: '花崗岩の塀', value: 'granite_wall'},
{text: '安山岩の塀', value: 'andesite_wall'},
{text: '閃緑岩の塀', value: 'diorite_wall'},
{text: 'プリズマリンの塀', value: 'prismarine_wall'},
{text: 'エンドストーンレンガの塀', value: 'end_stone_brick_wall'},
{text: '泥レンガの塀', value: 'mud_brick_wall'},

// フェンス
{text: 'オークのフェンス', value: 'oak_fence'},
{text: 'シラカバのフェンス', value: 'birch_fence'},
{text: 'トウヒのフェンス', value: 'spruce_fence'},
{text: 'ジャングルのフェンス', value: 'jungle_fence'},
{text: 'アカシアのフェンス', value: 'acacia_fence'},
{text: 'ダークオークのフェンス', value: 'dark_oak_fence'},
{text: 'マングローブのフェンス', value: 'mangrove_fence'},
{text: 'サクラのフェンス', value: 'cherry_fence'},
{text: '竹のフェンス', value: 'bamboo_fence'},
{text: 'ネザーレンガのフェンス', value: 'nether_brick_fence'},
{text: '真紅のフェンス', value: 'crimson_fence'},
{text: '歪んだフェンス', value: 'warped_fence'}
];

console.log(`Total BUILDING_BLOCKS: ${BUILDING_BLOCKS_COMPREHENSIVE.length}`);
